version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: healthup-postgres
    environment:
      POSTGRES_USER: healthup_user
      POSTGRES_PASSWORD: healthup_password
      POSTGRES_DB: healthup_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U healthup_user -d healthup_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
