name: CI - Tests and Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma client
      run: npm run db:generate
    
    - name: Run tests
      run: npm test
      env:
        JWT_PRIVATE_KEY: "test-private-key"
        JWT_PUBLIC_KEY: "test-public-key"
        JWT_ACCESS_TOKEN_EXPIRES_IN: "15m"
        JWT_REFRESH_TOKEN_EXPIRES_IN: "7d"

    - name: Run build
      run: npm run build

    - name: Debug - Check structure
      run: |
        echo "=== Current directory ==="
        pwd
        echo "=== tsconfig.json content ==="
        cat tsconfig.json
        echo "=== Source structure ==="
        find src -name "*.ts" | head -20
        echo "=== Check specific files ==="
        ls -la src/shared/helpers/ || echo "helpers folder not found"
        ls -la src/shared/middlewares/ || echo "middlewares folder not found"
        echo "=== TypeScript config check ==="
        npx tsc --showConfig

    # - name: Check TypeScript types
    #   run: npx tsc --noEmit --project tsconfig.json